# Generated by Django 4.0.3 on 2023-08-03 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_client', models.CharField(max_length=100)),
                ('review', models.TextField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 3, 9, 14, 10, 886426, tzinfo=utc))),
            ],
        ),
    ]
