# Generated by Django 4.0.3 on 2023-08-07 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_date_alter_review_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 8, 1, 1, 497092, tzinfo=utc)),
        ),
    ]
