# Generated by Django 4.0.3 on 2023-08-08 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_alter_review_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 11, 24, 14, 36076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 11, 24, 13, 956073, tzinfo=utc)),
        ),
    ]
